---
title: 'N Cycle Expt: Site Map'
author: "Stephanie J. Wilson"
date: '2023-08-01'
output: html_document
---
## Set Up
```{r setup, include=FALSE}
#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", 
#"ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))

library(ggplot2)
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library(ggspatial)

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

```

## Build Site Map
```{r}
sites <- read.csv("Site_Locations.csv")
head(sites)

map <- ggplot(data = world) +
    geom_sf() + 
    geom_point(data=sites, x=sites$Long, y=sites$Latitude, size=3.5) + 
    geom_text(data= sites,aes(x=(sites$Long + 0.3), y=(sites$Latitude + 0.15), label=sites$Site),
    color = "black", fontface = "bold", check_overlap = FALSE) + 
    labs(x=" ", y=" ") +
    annotation_scale() +
    annotation_north_arrow(location = "bl", which_north = "true", 
        pad_x = unit(0.15, "in"), pad_y = unit(0.25, "in"),
        style = north_arrow_fancy_orienteering)  +
    coord_sf(xlim = c(-77.906228, -74.643288), ylim = c(36.703980, 39.720171))


map





```

