---
title: "COMPASS_Synoptic_SEAL_Data_Analysis_Soil KCl Extracts"
author: "Stephanie J. Wilson"
date: '2023-03-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Information
```{r}
#######################################################################################
####### COMPASS Synoptic 
####### Chesapeake Bay Sites
####### Data Analysis Code: Porewater Nutrients 
####### MONTH: Soil KCl Extracts 
##############################################################################################


############################# Information ##################################
#Author: Stephanie J. Wilson
#Edited: 20220727

#Samples taken from Lysimeters & Sippers at CB Synoptic Sites
#Samples were filtered with 0.45 uM, kept on ice, frozen until analysis
#Field Protocol: 
#Samples Analyzed on a SEAL discrete auto analyzer 
#Lab Protocol: https://docs.google.com/document/d/1VaJT7Wb9AcdmM1tgsR_9ZtQ6kwcaoNmp/edit?usp=sharing&ouid=108994740386869376571&rtpof=true&sd=true
#NOx method = https://drive.google.com/file/d/1sicqBFnzVxmDd5I2_pu8s8pj7iNOAuhF/view?usp=sharing
#NH4 method = https://drive.google.com/file/d/1ENGemUEvm_rffZqv3lz9BjD0pAMX5nzu/view?usp=sharing
#PO4 method = https://drive.google.com/file/d/1m3gXDZnJoIo_QmyhvZG4HRgGShCzm9Wq/view?usp=sharing
#Units from SEAL = mg/L and converted to uMoles/L
```

## QAQC on Slopes - diregard this chunk for KCl bc just one run and stds looked good 
```{r}
library(ggplot2)
library(data.table)
library(here)

#read in datafile with all the slopes 
qlog <- read.csv(here("Soil Characteristics Data" ,"SERC_SEAL_STDs_Log.csv"))
head(qlog)

#pull out each method 
qNH3 <- qlog[qlog$Analysis %like% "NH3", ]
head(qNH3)

qPO4 <- qlog[qlog$Analysis %like% "PO4", ]
head(qPO4)

qNOx <- qlog[qlog$Analysis %like% "V-Nox", ]
head(qNOx)

########### NH3
#plot the slopes to make sure there are no crazy outliers 
slope1 <- ggplot(data=qNH3, aes(x=Date, y=Slope)) +
           #geom_line()+
            geom_point(aes(size=3)) + 
            theme_classic() + ylim(0, 5) + 
           theme(legend.position="none") + 
           ggtitle("NH3 Slopes")
  
slope1

#plot the intercepts to make sure there are no crazy outliers 
int1 <- ggplot(data=qNH3, aes(x=Date, y=Intercept)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(-0.5,0.5) + 
  theme(legend.position="none")+ 
  ggtitle("NH3 Intercepts")

int1

#plot the R2s to make sure there are no crazy outliers 
Rsq1 <- ggplot(data=qNH3, aes(x=Date, y=R2)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(0.75, 1.25) + 
  theme(legend.position="none")+ 
  ggtitle("NH3 R2s")

Rsq1

########### PO4
slope2 <- ggplot(data=qNH3, aes(x=Date, y=Slope)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(0, 5) + 
  theme(legend.position="none")+ 
  ggtitle("PO4 Slopes")

slope2

#plot the intercepts to make sure there are no crazy outliers 
int2 <- ggplot(data=qNH3, aes(x=Date, y=Intercept)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(-0.5,0.5) + 
  theme(legend.position="none")+ 
  ggtitle("PO4 Intercepts")

int2

#plot the R2s to make sure there are no crazy outliers 
Rsq2 <- ggplot(data=qNH3, aes(x=Date, y=R2)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(0.75, 1.25) + 
  theme(legend.position="none")+ 
  ggtitle("PO4 R2s")

Rsq2

########### NOx
slope3 <- ggplot(data=qNH3, aes(x=Date, y=Slope)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(0, 5) + 
  theme(legend.position="none")+ 
  ggtitle("NOx Slopes")

slope3

#plot the intercepts to make sure there are no crazy outliers 
int3 <- ggplot(data=qNH3, aes(x=Date, y=Intercept)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(-0.5,0.5) + 
  theme(legend.position="none")+ 
  ggtitle("NOx Intercepts")

int3

#plot the R2s to make sure there are no crazy outliers 
Rsq3 <- ggplot(data=qNH3, aes(x=Date, y=R2)) +
  #geom_line()+
  geom_point(aes(size=3)) + 
  theme_classic() + ylim(0.75, 1.25) + 
  theme(legend.position="none")+ 
  ggtitle("NOx R2s")

Rsq3



```

## Code Set up 
```{r}

#packages:
library(ggplot2)
library(dplyr)
library(data.table)
library(matrixStats)
library(gridExtra)
library(ggpubr)
library(grid)
library(here)

```

## KCl Ammonia
```{r}

#read in data 
file1 <- read.csv(here("Soil Characteristics Data" ,"COMPASS_NExpt_KCl_Nuts_NH4.csv"))
#Quick look at dataframe
head(file1)
#take out only the columns that we need 
dat1 <- file1[ ,c(1,4,6,7, 12, 13)]
# assigning new names to the columns of the data frame
colnames(dat1) <- c('Run_Info','Sample_Name','Conc', "Abs", "Units", "Test")
head(dat1)


alldat <- rbind(dat1)

#Pull out standards 
stds <- alldat[alldat$Sample_Name %like% "Standard", ]
head(stds)


#Pull out samples 
alldat2 <- alldat[alldat$Sample_Name %like% "MSM_", ]
alldat2 <- rbind(alldat2, (alldat[alldat$Sample_Name %like% "GWI_", ]))
alldat2 <- rbind(alldat2, (alldat[alldat$Sample_Name %like% "GCW", ]))
alldat2 <- rbind(alldat2, (alldat[alldat$Sample_Name %like% "SWH_", ]))
head(alldat2)

```

## NOx
```{r}

#read in data 
Nfile1 <- read.csv(here("Soil Characteristics Data" ,"COMPASS_NExpt_KCl_Nuts_NOx.csv"))
#Quick look at dataframe
head(Nfile1)
#take out only the columns that we need 
Ndat1 <- Nfile1[ ,c(1,4,6,7, 12, 13)]
# assigning new names to the columns of the data frame
colnames(Ndat1) <- c('Run_Info','Sample_Name','Conc', "Abs", "Units", "Test")
head(Ndat1)

Nalldat <- rbind(Ndat1)

#Pull out standards 
Nstds <- Nalldat[Nalldat$Sample_Name %like% "Standard", ]
head(Nstds)


#Pull out samples 
Nalldat2 <- Nalldat[Nalldat$Sample_Name %like% "MSM_", ]
Nalldat2 <- rbind(Nalldat2, (Nalldat[Nalldat$Sample_Name %like% "GWI_", ]))
Nalldat2 <- rbind(Nalldat2, (Nalldat[Nalldat$Sample_Name %like% "GCW", ]))
Nalldat2 <- rbind(Nalldat2, (Nalldat[Nalldat$Sample_Name %like% "SWH_", ]))
head(Nalldat2)


```

## Constants 
```{r}

N_mw <- 14.0067   # molecular weight of N 

P_mw <- 30.973762  # molecular weight of P 

Con1 <- 1000       # conversion factor value

Con2 <- 1000000    # conversion factor value 

```

## Convert Data from mg/L to uM 
```{r}
head(alldat2)
head(Nalldat2)

#subset by test
NH4samples <- subset(alldat2, Test == "KCl Ammonia 10")
head(NH4samples)

NOXsamples <- subset(Nalldat2, Test == "KCL NO3_NO2 2")
head(NOXsamples)


NH4samples$Conc_uM <- (((as.numeric(NH4samples$Conc))/Con1)/N_mw)*Con2
head(NH4samples)

NOXsamples$Conc_uM_raw <- (((as.numeric(NOXsamples$Conc))/Con1)/N_mw)*Con2
head(NOXsamples)

#add step to make negative values equal to bd (below detection) and replace with zeros 
NOXsamples$Conc_uM <- ifelse(NOXsamples$Conc_uM_raw<0, 0, (NOXsamples$Conc_uM_raw) )
head(NOXsamples)
```

## Pull all data back together and add flags
```{r}

#pull out the columns we want from each dataframe 
NH4_pull <- NH4samples[ ,c(2,3,7) ]
head(NH4_pull)

#PO4_pull <- PO4samples[ ,c(2,3,7) ]
#head(PO4_pull)

NOX_pull <- NOXsamples[ ,c(2,3,8) ]
head(NOX_pull)


#Bring all this data back together: 
all_data <- merge(NH4_pull,NOX_pull , by="Sample_Name", all.x=TRUE)
#all_data <- merge(all_data,PO4_pull , by="Sample_Name", all.x=TRUE)
head(all_data)

colnames(all_data) <- c("Sample_Name", "NH3_mgL", "NH3_uM", "NOx_mgL", "NOx_uM")
head(all_data)


#add in an if then statement that tells us if they are within the range of the test - check this after doing this line
all_data$NH3_range <- ifelse(all_data$NH3_mgL<0.04, "bdl",  ifelse(all_data$NH3_mgL>10, "adl", "Within_Range")) 
#all_data$PO4_range <- ifelse(all_data$PO4_mgL<0.003, "bdl",  ifelse(all_data$PO4_mgL>3, "adl", "Within_Range")) 
all_data$NOx_range <- ifelse(all_data$NOx_mgL<0.025, "bdl",  ifelse(all_data$NOx_mgL>1, "adl", "Within_Range"))
head(all_data)
```

## Take an initial look at concentrations 
```{r}
#plot data to get a sense of any outliers 
NH3look <- ggplot(data=all_data, aes(x=Sample_Name, y=NH3_uM)) +
  geom_bar(stat="identity") + 
  theme_classic() + ylim(-10, 200) + 
  theme(legend.position="none") + 
  ggtitle("Sample NH3 Concentrations")
NH3look

#PO4look <- ggplot(data=all_data, aes(x=Sample_Name, y=PO4_uM)) +
 # geom_bar(stat="identity") + 
  #theme_classic() + ylim(-2, 50) + 
#  theme(legend.position="none") + 
#  ggtitle("Sample PO4 Concentrations")
#PO4look

NOXlook <- ggplot(data=all_data, aes(x=Sample_Name, y=NOx_uM)) +
  geom_bar(stat="identity") + 
  theme_classic() + ylim(-2, 2) + 
  theme(legend.position="none") + 
  ggtitle("Sample NOx Concentrations")
NOXlook


```

## Pull out data you need, make IDs 
```{r}

head(all_data)

#out <- all_data[ ,c(1,3,5,7,8,9,10)]
#head(out)

#for steph <- pull out identifiers of the sample names 
#pull the sample ID and separate it by the underscores 
IDs <- data.frame(do.call('rbind', strsplit(as.character(all_data$Sample_Name),'_',fixed=TRUE)))
colnames(IDs) <- c("Site" , "Zone", "Replicate")
#IDs$Month <- ifelse(IDs$Date == 202210,"October","November")
#IDs$Month <- "September"
head(IDs)

#rejoin them to the dataframe
alldat <- cbind(IDs, all_data)
head(alldat)



```

## Export final data with flags 
```{r}

#Export Data
write.csv(alldat, file= here("Soil Characteristics Data" , "COMPASS_Synoptic_CB_NExpt_KClExtracts.csv") )

```




